name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - "neeraj-testing/**.js"
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install Dependencies
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          zip -j deploy.zip ./neeraj-testing
          aws lambda update-function-code --function-name=neeraj-testing --zip-file=fileb://deploy.zip
