name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - "neeraj-testing/**"
      - "testing2/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2
        # with:
        #   files: |
        #     index.js
        #     neeraj-testing
      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done

        # - name: Run step only when files change.
        #   if: contains(steps.changed-files.outputs.modified_files, 'neeraj-testing/index.js')

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install Dependencies for neeraj-testing
        if: contains(steps.changed-files.outputs.modified_files, 'neeraj-testing/index.js')
        working-directory: neeraj-testing
        env:
          CI: true
        run: |
          ls
          npm ci
      - name: deploy neeraj-testing
        if: contains(steps.changed-files.outputs.modified_files, 'neeraj-testing/index.js')
        run: |
          ls
          cd neeraj-testing
          zip -r neeraj-testing.zip index.js package.json package-lock.json node_modules
          aws  lambda update-function-code --function-name=neeraj-testing --zip-file=fileb://neeraj-testing.zip

        ##checking for function2
      - name: Installing dependencies for testing2
        if: contains(steps.changed-files.outputs.modified_files, 'testing2/index.js')
        working-directory: testing2
        env:
          CI: true
        run: |
          ls
          npm ci
      - name: deploying testing2
        if: contains(steps.changed-files.outputs.modified_files, 'testing2/index.js')
        run: |
          ls
          cd testing2
          zip -r testing.zip index.js package.json package-lock.json node_modules
          aws lambda update-function-code --function-name=neeraj-testing2 --zip-file=fileb://testing.zip

  # job_for_neeraj-testing:
  #   name: Job for neeraj-testing
  #   if: contains(steps.changed-files.outputs.modified_files, 'neeraj-testing/index.js')
